# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-31 06:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gramapp', '0003_auto_20180129_0852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_bio',
            new_name='bio',
        ),
    ]
