# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-01 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gramapp', '0005_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, to='gramapp.Comments'),
        ),
        migrations.AlterField(
            model_name='image',
            name='likes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
