# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-02 15:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gramapp', '0007_auto_20180202_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liked',
            name='post',
        ),
        migrations.RemoveField(
            model_name='liked',
            name='user',
        ),
        migrations.DeleteModel(
            name='liked',
        ),
    ]
