# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-04 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gramapp', '0010_auto_20180204_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gramapp.Profile'),
        ),
    ]
